apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: wicks482/cartservice:latest
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart-service:6379"  # Updated Redis address
            - name: SERVICE_NAME
              value: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP
