apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
        - name: currency
          image: wicks482/currencyservice:latest
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: SERVICE_NAME
              value: currency
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  selector:
    app: currency-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: ClusterIP
