apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog-deployment
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
        - name: productcatalog
          image: wicks482/productcatalogservice:latest
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
            - name: SERVICE_NAME
              value: productcatalog
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog-service
spec:
  selector:
    app: productcatalog
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550
