apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: wicks482/shippingservice:latest # Replace with your Shipping Service image and tag
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: SERVICE_NAME
              value: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
