# emailservice-service Deployment in production namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-service-production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice-service
  template:
    metadata:
      labels:
        app: emailservice-service
    spec:
      containers:
        - name: emailservice
          image: wicks482/emailservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_NAME
              value: email
            # Add other environment variables for email service here
