# paymentservice-service Deployment in production namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-service-production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice-service
  template:
    metadata:
      labels:
        app: paymentservice-service
    spec:
      containers:
        - name: paymentservice
          image: wicks482/paymentservice:latest
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: SERVICE_NAME
              value: payment
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Add other environment variables for payment service here
