apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImQybGphM00wT0RJNk56a3lNelF5TnpVNE9BPT0ifX19
