apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-staging
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: wicks482/cartservice:latest
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart-service-staging:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-staging
  namespace: staging
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
